students/urls.py
"""Defines URL patterns for students"""

from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    # Page that shows all students
    path('', views.students, name='students'),
    # Detail page for a single student
    path('students/<int:student_id>/', views.student, name='student'),
    # Page for adding a new student
    path('new_student/', views.new_student, name='new_student'),
    # Page for editing a university
    path('edit_student/<int:student_id>/', views.edit_student, name="edit_student"),
    # Page for deleting a student
    path('delete_student/<int:student_id>/', views.delete_student, name="delete_student"),
]

university_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin page
    path('admin/', admin.site.urls),
    # users page
    path('users/', include('users.urls')),
    # page for universities
    path('', include('universities.urls')),
    # page for students
    path('students/', include('students.urls')),
    # page for departments
    path('departments/', include('departments.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

students/models.py
import sys
sys.path.append("..")
from django.db import models
from django.contrib.auth.models import User
from classes.models import Class
from departments.models import Department


# Create your models here.
class Student(models.Model):
    """A student object to hold student information"""
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)
    major = models.CharField(max_length=50)
    FRESHMAN = 'FR'
    SOPHOMORE = 'SO'
    JUNIOR = 'JR'
    SENIOR = 'SR'
    GRADUATE = 'GR'
    YEAR_IN_SCHOOL_CHOICES = [
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
        (GRADUATE, 'Graduate'),
    ]
    year_in_school = models.CharField(
        max_length=2,
        choices=YEAR_IN_SCHOOL_CHOICES,
        default=FRESHMAN,
    )
    date_enrolled = models.DateField(auto_now_add=False)
    major_department = models.ForeignKey(Department, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name.capitalize()} - {self.year_in_school} - {self.major}"

students/forms.py
from django import forms

from .models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'email', 'major', 'year_in_school', 'date_enrolled', 'major_department']
        labels = {'name': 'Name', 'email': 'Email', 'major': 'Major', 'year_in_school': 'Year in school',
                  'date_enrolled': 'Date enrolled (YYYY-MM-DD)', 'major_department': 'Major department'}

students/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Student
from .forms import StudentForm


# Create your views here.
@login_required
def students(request):
    """Show all students"""
    students = Student.objects.filter(owner=request.user).order_by('name')
    context = {'students': students}
    return render(request, 'students/students.html', context)


@login_required
def student(request, student_id):
    """Show details on a specific student"""
    student = get_object_or_404(Student, id=student_id)
    # Check to make sure the student belongs to the current user
    if student.owner != request.user:
        raise Http404
    context = {'student': student}
    return render(request, 'students/student.html', context)


@login_required
def new_student(request):
    """Add a new student"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = StudentForm
    else:
        # POST data submitted; process data
        form = StudentForm(data=request.POST)
        if form.is_valid():
            new_student = form.save(commit=False)
            new_student.owner = request.user
            new_student.save()
            return redirect('students:students')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'students/new_student.html', context)


@login_required
def edit_student(request, student_id):
    """Edit an existing student"""
    student = Student.objects.get(id=student_id)
    # Check to make sure the student is owned by the user
    if student.owner != request.user:
        raise Http404
    name = student.name
    email = student.email
    major = student.major
    year_in_school = student.year_in_school
    date_enrolled = student.date_enrolled
    major_department = student.major_department

    if request.method != 'POST':
        # initial request; pre-fill form with current entry
        form = StudentForm(instance=student)
    else:
        # POST data submitted, process data
        form = StudentForm(instance=student, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('students:student', student_id=student.id)

    context = {'student': student, 'name': name, 'email': email, 'major': major, 'year_in_school': year_in_school,
               'date_enrolled': date_enrolled, 'major_department': major_department, 'form': form}
    return render(request, 'students/edit_student.html', context)


@login_required
def delete_student(request, student_id):
    student = Student.objects.get(id=student_id)
    # Check to make sure the student is owned by the user
    if student.owner != request.user:
        raise Http404
    # BA-LETED
    Student.objects.get(id=student_id).delete()
    # After delete, redirect back to main students page
    students = Student.objects.filter(owner=request.user).order_by('name')
    context = {'students': students}
    return render(request, 'students/students.html', context)

students/templates/students/edit_student.html
{% extends "universities/base.html" %}

{% block content %}

<p><a href="{% url 'students:student' student.id %}">{{ student }}</a></p>
<p>Edit university:</p>

<form action="{% url 'students:edit_student' student.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

students/templates/students/new_student.html
{% extends "universities/base.html" %}

{% block content %}

<p>Add a new student</p>

<form action="{% url 'students:new_student' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Student</button>
</form>

{% endblock content %}

students/templates/students/student.html
{% extends "universities/base.html" %}

{% block page_header %}
  <h2>Student Detailed View</h2>
{% endblock page_header %}

{% block content %}

<div class="card mb-3">
    <h4 class="card-header">Student Name: {{student.name}}</h4>
    <h5>Email: {{student.email}}</h5>
    <h5>Major: {{student.major}}</h5>
    <h5>Major: {{student.year_in_school}}</h5>
    <h5>Date enrolled: {{student.date_enrolled}}</h5>

</div>

<p>
    <a href="{% url 'students:edit_student' student.id %}"><button type="button" class="btn btn-primary">Edit Student</button></a>
    <a href="{% url 'students:delete_student' student.id %}"
       onclick="return confirm('Are you sure you want to delete this Student?')">
        <button type="button" class="btn btn-primary">Delete Student</button></a>
</p>

{% endblock content %}

students/templates/students/students.html
{% extends "universities/base.html" %}

{% block page_header %}
  <h2>Students</h2>
{% endblock page_header %}

{% block content %}

<ul>
  {% for student in students %}
    <li>
      <h3>
        <a href="{% url 'students:student' student.id %}">{{student.name}} - {{student.year_in_school}} - {{student.major}} </a>
      </h3>
    </li>
  {% empty %}
    <li>
      <h3>
        No students have been added yet
      </h3>
    </li>
  {% endfor %}
</ul>
<br>
<h3><a href="{% url 'students:new_student'%}">Add a new student</a></h3>

{% endblock content %}