departments/urls.py
"""Defines URL patterns for departments"""

from django.urls import path

from . import views

app_name = "departments"
urlpatterns = [
    # Page that shows all departments
    path('', views.departments, name='departments'),
    # Detail page for a single department
    path('departments/<int:department_id>/', views.department, name='department'),
    # Page for adding a new department
    path('new_department/', views.new_department, name='new_department'),
    # Page for editing a department
    path('edit_department/<int:department_id>/', views.edit_department, name="edit_department"),
    # Page for deleting a department
    path('delete_department/<int:department_id>/', views.delete_department, name="delete_department"),
]

students/urls.py
"""Defines URL patterns for students"""

from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    # Page that shows all students
    path('', views.students, name='students'),
    # Detail page for a single student
    path('students/<int:student_id>/', views.student, name='student'),
    # Page for adding a new student
    path('new_student/', views.new_student, name='new_student'),
    # Page for editing a university
    path('edit_student/<int:student_id>/', views.edit_student, name="edit_student"),
    # Page for deleting a student
    path('delete_student/<int:student_id>/', views.delete_student, name="delete_student"),
]

universities/urls.py
"""Defines URL patterns for universities"""

from django.urls import path

from . import views

app_name = "universities"
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Page that shows all Universities
    path('universities/', views.universities, name='universities'),
    # Detail page for a single university
    path('universities/<int:university_id>/', views.university, name='university'),
    # Page for adding a new university
    path('new_university/', views.new_university, name='new_university'),
    # Page for editing a university
    path('edit_university/<int:university_id>/', views.edit_university, name="edit_university"),
    # Page for deleting a university
    path('delete_university/<int:university_id>/', views.delete_university, name="delete_university"),
    # Page for exporting a university to csv
    path('export_university/<int:university_id>/', views.export_university, name="export_university"),
]

university_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin page
    path('admin/', admin.site.urls),
    # users page
    path('users/', include('users.urls')),
    # page for universities
    path('', include('universities.urls')),
    # page for students
    path('students/', include('students.urls')),
    # page for departments
    path('departments/', include('departments.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

universities/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class University(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "universities"

    def __str__(self):
        return self.name

universities/forms.py
from django import forms

from .models import University

class UniversityForm(forms.ModelForm):
    class Meta:
        model = University
        fields = ['name']
        labels = {'name': 'University Name'}

universities/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.contrib import messages
import csv
from .models import University
from students.models import Student
from departments.models import Department
from .forms import UniversityForm

# Create your views here.
def index(request):
    """The home page for the university system"""
    return render(request, 'universities/index.html')

@login_required
def universities(request):
    """Show all universities"""
    universities = University.objects.filter(owner=request.user).order_by('name')
    context = {'universities': universities}
    return render(request, 'universities/universities.html', context)


@login_required
def university(request, university_id):
    """Show a specific university"""
    uni = get_object_or_404(University, id=university_id)
    # Check to make sure the university belongs to the current user
    if uni.owner != request.user:
        raise Http404
    departments = Department.objects.filter(university=uni)
    students = []
    for dept in departments:
        if Student.objects.filter(major_department=dept):
            student = Student.objects.filter(major_department=dept).values()
            students.append(student)
    context = {'uni': uni, 'students': students, 'departments': departments}
    return render(request, 'universities/university.html', context)


@login_required
def new_university(request):
    """Add a new university"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = UniversityForm
    else:
        # POST data submitted; process data
        form = UniversityForm(data=request.POST)
        if form.is_valid():
            new_university = form.save(commit=False)
            new_university.owner = request.user
            new_university.save()
            return redirect('universities:universities')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'universities/new_university.html', context)


@login_required
def edit_university(request, university_id):
    """Edit an existing university"""
    university = University.objects.get(id=university_id)
    # Check to make sure the university is owned by the user
    if university.owner != request.user:
        raise Http404
    name = university.name

    if request.method != 'POST':
        # initial request; pre-fill form with current entry
        form = UniversityForm(instance=university)
    else:
        # POST data submitted, process data
        form = UniversityForm(instance=university, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('universities:university', university_id=university.id)

    context = {'university': university, 'name': name, 'form': form}
    return render(request, 'universities/edit_university.html', context)


@login_required
def delete_university(request, university_id):
    university = University.objects.get(id=university_id)
    # Check to make sure the university is owned by the user
    if university.owner != request.user:
        raise Http404
    # BA-LETED
    University.objects.get(id=university_id).delete()
    # After delete, redirect back to main universities page
    universities = University.objects.filter(owner=request.user).order_by('name')
    context = {'universities': universities}
    return render(request, 'universities/universities.html', context)


@login_required
def export_university(request, university_id):
    uni = University.objects.get(id=university_id)
    filename = uni.name + "_export.csv"
    departments = Department.objects.filter(university=uni)
    students = []
    try:
        with open(filename, 'w', newline='\n') as f:
            csv_writer = csv.writer(f, delimiter=",")
            csv_writer.writerow(["Department", "Student Name", "Email", "Major", "Year", "Date Enrolled"])
            for dept in departments:
                if Student.objects.filter(major_department=dept):
                    students.append(Student.objects.filter(major_department=dept).values())
                    for student in Student.objects.filter(major_department=dept):
                        csv_writer.writerow([dept.name, student.name, student.email, student.major,
                                             student.year_in_school, student.date_enrolled])
        messages.success(request, 'Successfully Exported the University!')
    except Exception as e:
        print(f"Error while exporting university file: {e}")

    context = {'uni': uni, 'students': students, 'departments': departments}
    return render(request, 'universities/university.html', context)

universities/templates/universities/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>University System 9000</title>

  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}

</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
    <a class="navbar-brand" href="{% url 'universities:index' %}">University System 9000</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'universities:universities' %}">Universities</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'departments:departments' %}">Departments</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'students:students' %}">Students</a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <span class="navbar-text">Hello, {{ user.username }}</span>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <main role="main" class="container">
      <div class="pb-2 mb-2 border-bottom">
        {% block page_header %}{% endblock page_header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
  </main>
</body>
</html>

universities/templates/universities/edit_university.html
{% extends "universities/base.html" %}

{% block content %}

<p><a href="{% url 'universities:university' university.id %}">{{ university }}</a></p>
<p>Edit university:</p>

<form action="{% url 'universities:edit_university' university.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

universities/templates/universities/index.html
{% extends "universities/base.html" %}

{% block page_header %}

  <div class="jumbotron">
    <h1 class="display-3">University System 9000</h1>
    <p class="lead">Are you tired of trying to keep track of all your universities, departments, and students?
        Look no further than the University System 9000. We will keep track of everything so you don't have to</p>
      <p class="small">JakeCorp cannot be held liable for any loss of life due to the University System 9000 gaining sentience</p>
    {% if user.is_authenticated %}
      <a class="btn btn-lg btm-primary" href="{% url 'universities:new_university' %}" role="button">Add a university &raquo;</a>
    {% else %}
      <a class="btn btn-lg btm-primary" href="{% url 'users:register' %}" role="button">Register &raquo;</a>
      <a class="btn btn-lg btm-primary" href="{% url 'users:login' %}" role="button">Login &raquo;</a>
    {% endif %}
  </div>

{% endblock page_header %}

universities/templates/universities/new_university.html
{% extends "universities/base.html" %}

{% block content %}

<p>Add a new university</p>

<form action="{% url 'universities:new_university' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add University</button>
</form>

{% endblock content %}

universities/templates/universities/universities.html
{% extends "universities/base.html" %}

{% block page_header %}
  <h2>Universities</h2>
{% endblock page_header %}

{% block content %}

<ul>
  {% for university in universities %}
    <li>
      <h3>
        <a href="{% url 'universities:university' university.id %}">{{university}}</a>
      </h3>
    </li>
  {% empty %}
    <li>
      <h3>
        No universities have been added yet
      </h3>
    </li>
  {% endfor %}
</ul>
<br>
<h3><a href="{% url 'universities:new_university' %}">Add a new university</a></h3>

{% endblock content %}

universities/templates/universities/university.html
{% extends "universities/base.html" %}

{% block page_header %}
  <h2>{{ uni.name }}</h2>
{% endblock page_header %}

{% block content %}

<ul>
  {% for department in departments %}
    <div class="card mb-3">
        <h4 class="card-header"> {{ department.name }}
            <small><a href="{% url 'departments:edit_department' department.id %}">Edit department</a></small>
             </h4>
            <h5 class="card-body" style="padding-top: 0" style="padding-bottom: 0">Enrolled Students:</h5>
            {% for student in students %}
                {% for s in student %}
                    {% if s.major_department_id == department.id %}
                      <h6 class="card-body" style="padding-top: 0">
                          <a href="{% url 'students:student' s.id %}"> {{ s.name }} - {{ s.major }} </a>
                      </h6>
                    {% endif %}
                {% endfor %}
            {% empty%}
                <h6 style="padding-top: 0">No students are currently enrolled</h6>
            {% endfor %}
    </div>
  {% empty%}
    <h4 class="card-header">No current departments</h4>
  {% endfor %}
</ul>

{% if messages %}
    {% for message in messages %}
        {% if message.tags %}  <script>alert("{{ message }}")</script> {% endif %}
    {% endfor %}
{% endif %}

<p>
    <a href="{% url 'universities:edit_university' uni.id %}"><button type="button" class="btn btn-primary">Edit University</button></a>
    <a href="{% url 'universities:export_university' uni.id %}"><button type="button" class="btn btn-primary">Export University</button></a>
    <a href="{% url 'universities:delete_university' uni.id %}"
       onclick="return confirm('Are you sure you want to delete this university? This will delete all departments and students associated with this university')">
        <button type="button" class="btn btn-primary">Delete University</button></a>
</p>

{% endblock content %}