departments/urls.py
"""Defines URL patterns for departments"""

from django.urls import path

from . import views

app_name = "departments"
urlpatterns = [
    # Page that shows all departments
    path('', views.departments, name='departments'),
    # Detail page for a single department
    path('departments/<int:department_id>/', views.department, name='department'),
    # Page for adding a new department
    path('new_department/', views.new_department, name='new_department'),
    # Page for editing a department
    path('edit_department/<int:department_id>/', views.edit_department, name="edit_department"),
    # Page for deleting a department
    path('delete_department/<int:department_id>/', views.delete_department, name="delete_department"),
]

students/urls.py
"""Defines URL patterns for students"""

from django.urls import path

from . import views

app_name = "students"
urlpatterns = [
    # Page that shows all students
    path('', views.students, name='students'),
    # Detail page for a single student
    path('students/<int:student_id>/', views.student, name='student'),
    # Page for adding a new student
    path('new_student/', views.new_student, name='new_student'),
    # Page for editing a university
    path('edit_student/<int:student_id>/', views.edit_student, name="edit_student"),
    # Page for deleting a student
    path('delete_student/<int:student_id>/', views.delete_student, name="delete_student"),
]

university_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # admin page
    path('admin/', admin.site.urls),
    # users page
    path('users/', include('users.urls')),
    # page for universities
    path('', include('universities.urls')),
    # page for students
    path('students/', include('students.urls')),
    # page for departments
    path('departments/', include('departments.urls')),
]

users/urls.py
"""Defines URL patterns for users"""

from django.urls import path, include

from . import views

app_name = "users"
urlpatterns = [
    # Include default auth urls
    path('', include('django.contrib.auth.urls')),
    # Registration page
    path('register/', views.register, name='register'),
]

departments/models.py
import sys
sys.path.append("..")
from django.db import models
from django.contrib.auth.models import User
from universities.models import University


# Create your models here.
class Department(models.Model):
    name = models.CharField(max_length=50)
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Returns a string representation of the department"""
        return f"{self.university.name} {self.name} department"

departments/forms.py
from django import forms

from .models import Department

class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = ['name', 'university']
        labels = {'name': 'Department Name', 'university': 'University Name'}

departments/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Department
from students.models import Student
from .forms import DepartmentForm


# Create your views here.
@login_required
def departments(request):
    """Show all departments"""
    departments = Department.objects.filter(owner=request.user).order_by('name')
    context = {'departments': departments}
    return render(request, 'departments/departments.html', context)


@login_required
def department(request, department_id):
    """Show details on a specific department"""
    department = get_object_or_404(Department, id=department_id)
    # Check to make sure the department belongs to the current user
    if department.owner != request.user:
        raise Http404
    students = Student.objects.filter(major_department=department)
    context = {'department': department, 'students': students}
    return render(request, 'departments/department.html', context)


@login_required
def new_department(request):
    """Add a new department"""
    if request.method != 'POST':
        # No data submitted; create a blank form
        form = DepartmentForm
    else:
        # POST data submitted; process data
        form = DepartmentForm(data=request.POST)
        if form.is_valid():
            new_department = form.save(commit=False)
            new_department.owner = request.user
            new_department.save()
            return redirect('departments:departments')

    # Display a blank or invalid form
    context = {'form': form}
    return render(request, 'departments/new_department.html', context)


@login_required
def edit_department(request, department_id):
    """Edit an existing department"""
    department = Department.objects.get(id=department_id)
    # Check to make sure the department is owned by the user
    if department.owner != request.user:
        raise Http404
    name = department.name
    university = department.university

    if request.method != 'POST':
        # initial request; pre-fill form with current entry
        form = DepartmentForm(instance=department)
    else:
        # POST data submitted, process data
        form = DepartmentForm(instance=department, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('departments:department', department_id=department.id)

    context = {'department': department, 'name': name, 'university': university, 'form': form}
    return render(request, 'departments/edit_department.html', context)


@login_required
def delete_department(request, department_id):
    department = Department.objects.get(id=department_id)
    # Check to make sure the department is owned by the user
    if department.owner != request.user:
        raise Http404
    # BA-LETED
    Department.objects.get(id=department_id).delete()
    # After delete, redirect back to main departments page
    departments = Department.objects.filter(owner=request.user).order_by('name')
    context = {'departments': departments}
    return render(request, 'departments/departments.html', context)

departments/templates/departments/department.html
{% extends "universities/base.html" %}

{% block content %}

<div class="card mb-3">
    <h2 class="card-header">{{ department.name }}</h2>
    <h2 class="card-body">University: {{ department.university }}</h2>
    <h3 class="card-body" style="padding-top: 0">Enrolled students:</h3>
    {% for student in students %}
        <h5 class="card-body" style="padding-top: 0">
            <a href="{% url 'students:student' student.id %}">{{ student.name }} - {{ student.major }}</a></h5>
    {% empty%}
        <h5 class="card-body">No students are currently enrolled</h5>
  {% endfor %}
</div>
<p>
    <a href="{% url 'departments:edit_department' department.id %}"><button type="button" class="btn btn-primary">Edit Department</button></a>
    <a href="{% url 'departments:delete_department' department.id %}"
       onclick="return confirm('Are you sure you want to delete this department? This will delete all students associated with this department')">
        <button type="button" class="btn btn-primary">Delete Department</button></a>
</p>

{% endblock content %}

departments/templates/departments/departments.html
{% extends "universities/base.html" %}

{% block page_header %}
  <h2>Departments</h2>
{% endblock page_header %}

{% block content %}


<ul>
  {% for department in departments %}
    <li>
      <h3>
        <a href="{% url 'departments:department' department.id %}">{{department.name}} - {{department.university}}</a>
      </h3>
    </li>
  {% empty %}
    <li>
      <h3>
        No departments have been added yet
      </h3>
    </li>
  {% endfor %}
</ul>
<br>
<h3><a href="{% url 'departments:new_department'%}">Add a new department</a></h3>

{% endblock content %}

departments/templates/departments/edit_department.html
{% extends "universities/base.html" %}

{% block content %}

<p><a href="{% url 'departments:department' department.id %}">{{ department }}</a></p>
<p>Edit department:</p>

<form action="{% url 'departments:edit_department' department.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Save changes</button>
</form>

{% endblock content %}

departments/templates/departments/new_department.html
{% extends "universities/base.html" %}

{% block content %}

<p>Add a new department</p>

<form action="{% url 'departments:new_department' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Add Department</button>
</form>

{% endblock content %}